// Code generated by go-swagger; DO NOT EDIT.

/*
Copyright 2017 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ClusterDetails cluster details
// swagger:model ClusterDetails
type ClusterDetails struct {

	// k8
	K8 *Cluster `json:"k8,omitempty"`

	// workers
	Workers []*WorkerDetails `json:"workers"`
}

// Validate validates this cluster details
func (m *ClusterDetails) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateK8(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateWorkers(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ClusterDetails) validateK8(formats strfmt.Registry) error {

	if swag.IsZero(m.K8) { // not required
		return nil
	}

	if m.K8 != nil {

		if err := m.K8.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("k8")
			}
			return err
		}
	}

	return nil
}

func (m *ClusterDetails) validateWorkers(formats strfmt.Registry) error {

	if swag.IsZero(m.Workers) { // not required
		return nil
	}

	for i := 0; i < len(m.Workers); i++ {

		if swag.IsZero(m.Workers[i]) { // not required
			continue
		}

		if m.Workers[i] != nil {

			if err := m.Workers[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("workers" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *ClusterDetails) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ClusterDetails) UnmarshalBinary(b []byte) error {
	var res ClusterDetails
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
