// Code generated by go-swagger; DO NOT EDIT.

/*
Copyright 2017 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// StateDetails state details
// swagger:model StateDetails
type StateDetails struct {

	// nodes rollup
	NodesRollup *StateDetailsNodesRollup `json:"nodesRollup,omitempty"`

	// tkw rollup
	TkwRollup *StateDetailsTkwRollup `json:"tkwRollup,omitempty"`
}

// Validate validates this state details
func (m *StateDetails) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateNodesRollup(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateTkwRollup(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *StateDetails) validateNodesRollup(formats strfmt.Registry) error {

	if swag.IsZero(m.NodesRollup) { // not required
		return nil
	}

	if m.NodesRollup != nil {

		if err := m.NodesRollup.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("nodesRollup")
			}
			return err
		}
	}

	return nil
}

func (m *StateDetails) validateTkwRollup(formats strfmt.Registry) error {

	if swag.IsZero(m.TkwRollup) { // not required
		return nil
	}

	if m.TkwRollup != nil {

		if err := m.TkwRollup.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("tkwRollup")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *StateDetails) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *StateDetails) UnmarshalBinary(b []byte) error {
	var res StateDetails
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// StateDetailsNodesRollup state details nodes rollup
// swagger:model StateDetailsNodesRollup
type StateDetailsNodesRollup struct {

	// p r o v i s i o n i n g
	PROVISIONING int32 `json:"PROVISIONING,omitempty"`
}

// Validate validates this state details nodes rollup
func (m *StateDetailsNodesRollup) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *StateDetailsNodesRollup) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *StateDetailsNodesRollup) UnmarshalBinary(b []byte) error {
	var res StateDetailsNodesRollup
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// StateDetailsTkwRollup state details tkw rollup
// swagger:model StateDetailsTkwRollup
type StateDetailsTkwRollup struct {

	// p r o v i s i o n i n g
	PROVISIONING int32 `json:"PROVISIONING,omitempty"`
}

// Validate validates this state details tkw rollup
func (m *StateDetailsTkwRollup) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *StateDetailsTkwRollup) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *StateDetailsTkwRollup) UnmarshalBinary(b []byte) error {
	var res StateDetailsTkwRollup
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
